# Sample configuration for CedarHawk
startURL = "https://example.com"
maxDepth = 3
resultsFile = "results.json"

[ui]
expectedLayout = "default"
viewports = [
    { name = "desktop", width = 1920, height = 1080 },
    { name = "tablet", width = 768, height = 1024 },
    { name = "mobile", width = 375, height = 667 }
]

[logging]
level = "info"

